default_context:
  project_name: 'plann'
  project_slug: 'plann'
  domain_main: 'plann.com'
  domain_staging: 'stag.plann.com'
  docker_swarm_stack_name_main: 'plann-com'
  docker_swarm_stack_name_staging: 'stag-plann-com'
  secret_key: '8399d24765462020e50715ba5ee9673788d6b702b4813d67af7397230f52cc8c'
  first_superuser: 'admin@plann.com'
  first_superuser_password: '7^&$!laPnN#336253?q='
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.plann.com", "https://stag.plann.com", "https://plann.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@plann.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@plann.com'
  pgadmin_default_user_password: '7^&$!laPnN#336253?q='
  traefik_constraint_tag: 'plann.com'
  traefik_constraint_tag_staging: 'stag.plann.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:7^&$!laPnN#336253?q='
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
